spring:
  profiles:
    active: dev
  application:
    name: java-springboot-demo
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qq100600
    url: jdbc:mariadb://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml

logging:
  config: classpath:log4j2.xml
