spring:
  application:
    name: java-springboot-demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 
    url: jdbc:mariadb://192.168.0.47:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.0.47
    port: 6379

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml

logging:
  config: classpath:log4j2.xml
